version: "2"

services:
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - DEBUG="True"
      - HUGGINGFACE_HUB_CACHE=.cache
    volumes:
    - .:/app
