services:
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "30534:8000"
    environment:
      - DEBUG="True"
      - HUGGINGFACE_HUB_CACHE=.cache
